<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDmix8BZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDmix8BZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDmix8BZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDmix8BZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDmix8BZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'Dmix8BZ',
    'container.build_id' => 'fa1786cc',
    'container.build_time' => 1634809222,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDmix8BZ');
