<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA8dYG0U\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA8dYG0U/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA8dYG0U.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA8dYG0U\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA8dYG0U\App_KernelDevDebugContainer([
    'container.build_hash' => 'A8dYG0U',
    'container.build_id' => '1a56c3bc',
    'container.build_time' => 1635423890,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA8dYG0U');
