<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3Tsg6D1\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3Tsg6D1/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container3Tsg6D1.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container3Tsg6D1\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container3Tsg6D1\App_KernelProdContainer([
    'container.build_hash' => '3Tsg6D1',
    'container.build_id' => '58bcce68',
    'container.build_time' => 1639358302,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3Tsg6D1');
