<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
            ],
        ],
        'base' => [
            'js' => [
                '/build/runtime.js',
            ],
        ],
        'animaux' => [
            'js' => [
                '/build/runtime.js',
            ],
        ],
        'carte' => [
            'js' => [
                '/build/runtime.js',
            ],
        ],
        'chien' => [
            'js' => [
                '/build/runtime.js',
            ],
        ],
        'salon' => [
            'js' => [
                '/build/runtime.js',
            ],
        ],
        'landscape' => [
            'js' => [
                '/build/runtime.js',
            ],
        ],
    ],
],

]];
