<?php

namespace ContainerDmix8BZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ph1lUSXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ph1lUSX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ph1lUSX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'authenticator' => ['privates', 'App\\Security\\AppCustomAuthenticator', 'getAppCustomAuthenticatorService', true],
            'emailVerifier' => ['privates', 'App\\Security\\EmailVerifier', 'getEmailVerifierService', true],
            'guardHandler' => ['privates', 'security.authentication.guard_handler', 'getSecurity_Authentication_GuardHandlerService', true],
        ], [
            'authenticator' => 'App\\Security\\AppCustomAuthenticator',
            'emailVerifier' => 'App\\Security\\EmailVerifier',
            'guardHandler' => '?',
        ]);
    }
}
