<?php

namespace ContainerDmix8BZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ac4EosVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ac4EosV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ac4EosV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'annonceRepository' => ['privates', 'App\\Repository\\AnnonceRepository', 'getAnnonceRepositoryService', true],
            'evenementRepository' => ['privates', 'App\\Repository\\EvenementRepository', 'getEvenementRepositoryService', true],
        ], [
            'annonceRepository' => 'App\\Repository\\AnnonceRepository',
            'evenementRepository' => 'App\\Repository\\EvenementRepository',
        ]);
    }
}
