<?php

namespace ContainerDmix8BZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AcWOF6eService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.acWOF6e' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.acWOF6e'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'annonceRepository' => ['privates', 'App\\Repository\\AnnonceRepository', 'getAnnonceRepositoryService', true],
            'evenement' => ['privates', '.errored..service_locator.acWOF6e.App\\Entity\\Evenement', NULL, 'Cannot autowire service ".service_locator.acWOF6e": it references class "App\\Entity\\Evenement" but no such service exists.'],
        ], [
            'annonceRepository' => 'App\\Repository\\AnnonceRepository',
            'evenement' => 'App\\Entity\\Evenement',
        ]);
    }
}
