<?php

namespace Container3Tsg6D1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ca4Y9j2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.ca4Y9j2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ca4Y9j2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'evenement' => ['privates', '.errored..service_locator.ca4Y9j2.App\\Entity\\Evenement', NULL, 'Cannot autowire service ".service_locator.ca4Y9j2": it references class "App\\Entity\\Evenement" but no such service exists.'],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'mailerController' => ['services', 'App\\Controller\\MailerController', 'getMailerControllerService', true],
        ], [
            'evenement' => 'App\\Entity\\Evenement',
            'mailer' => '?',
            'mailerController' => 'App\\Controller\\MailerController',
        ]);
    }
}
