<?php

namespace Container3Tsg6D1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BemHZsFService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.BemHZsF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BemHZsF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'evenement' => ['privates', '.errored..service_locator.BemHZsF.App\\Entity\\Evenement', NULL, 'Cannot autowire service ".service_locator.BemHZsF": it references class "App\\Entity\\Evenement" but no such service exists.'],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'evenement' => 'App\\Entity\\Evenement',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
