<?php

namespace Container3Tsg6D1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FRTFtnuService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.fRTFtnu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fRTFtnu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'evenement' => ['privates', '.errored..service_locator.fRTFtnu.App\\Entity\\Evenement', NULL, 'Cannot autowire service ".service_locator.fRTFtnu": it references class "App\\Entity\\Evenement" but no such service exists.'],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'user' => ['privates', '.errored..service_locator.fRTFtnu.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.fRTFtnu": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'evenement' => 'App\\Entity\\Evenement',
            'mailer' => '?',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
