<?php

namespace Container3Tsg6D1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFavoriControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\FavoriController' shared autowired service.
     *
     * @return \App\Controller\FavoriController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/FavoriController.php';

        $container->services['App\\Controller\\FavoriController'] = $instance = new \App\Controller\FavoriController();

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->load('get_ServiceLocator_5nX7ca3Service'))->withContext('App\\Controller\\FavoriController', $container));

        return $instance;
    }
}
