<?php

namespace Container3Tsg6D1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlateformeControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\PlateformeController' shared autowired service.
     *
     * @return \App\Controller\PlateformeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/PlateformeController.php';

        $container->services['App\\Controller\\PlateformeController'] = $instance = new \App\Controller\PlateformeController();

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->load('get_ServiceLocator_5nX7ca3Service'))->withContext('App\\Controller\\PlateformeController', $container));

        return $instance;
    }
}
