<?php

namespace Container3Tsg6D1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegisterEventControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\RegisterEventController' shared autowired service.
     *
     * @return \App\Controller\RegisterEventController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/RegisterEventController.php';

        $container->services['App\\Controller\\RegisterEventController'] = $instance = new \App\Controller\RegisterEventController(($container->privates['App\\Security\\EmailVerifier'] ?? $container->load('getEmailVerifierService')));

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->load('get_ServiceLocator_5nX7ca3Service'))->withContext('App\\Controller\\RegisterEventController', $container));

        return $instance;
    }
}
