<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TriSelection extends \App\Entity\TriSelection implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\TriSelection' . "\0" . 'id', '' . "\0" . 'App\\Entity\\TriSelection' . "\0" . 'ageTri', '' . "\0" . 'App\\Entity\\TriSelection' . "\0" . 'nbrViewTri', '' . "\0" . 'App\\Entity\\TriSelection' . "\0" . 'dateAtCreatedTri', '' . "\0" . 'App\\Entity\\TriSelection' . "\0" . 'dateEventTri', '' . "\0" . 'App\\Entity\\TriSelection' . "\0" . 'lieuTri'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\TriSelection' . "\0" . 'id', '' . "\0" . 'App\\Entity\\TriSelection' . "\0" . 'ageTri', '' . "\0" . 'App\\Entity\\TriSelection' . "\0" . 'nbrViewTri', '' . "\0" . 'App\\Entity\\TriSelection' . "\0" . 'dateAtCreatedTri', '' . "\0" . 'App\\Entity\\TriSelection' . "\0" . 'dateEventTri', '' . "\0" . 'App\\Entity\\TriSelection' . "\0" . 'lieuTri'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TriSelection $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getLieuTri()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieuTri', []);

        return parent::getLieuTri();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieuTri($lieuTri): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieuTri', [$lieuTri]);

        parent::setLieuTri($lieuTri);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgeTri()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgeTri', []);

        return parent::getAgeTri();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgeTri($ageTri): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgeTri', [$ageTri]);

        parent::setAgeTri($ageTri);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbrViewTri()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbrViewTri', []);

        return parent::getNbrViewTri();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbrViewTri($nbrViewTri): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbrViewTri', [$nbrViewTri]);

        parent::setNbrViewTri($nbrViewTri);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAtCreatedTri()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAtCreatedTri', []);

        return parent::getDateAtCreatedTri();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAtCreatedTri($dateAtCreatedTri): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAtCreatedTri', [$dateAtCreatedTri]);

        parent::setDateAtCreatedTri($dateAtCreatedTri);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateEventTri()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateEventTri', []);

        return parent::getDateEventTri();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateEventTri($dateEventTri): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateEventTri', [$dateEventTri]);

        parent::setDateEventTri($dateEventTri);
    }

}
