<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Annonce extends \App\Entity\Annonce implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'titre', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'isFinish', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'atCreated', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'nbrViews', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'nomAnimal', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'espece', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'address', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'ville', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'pays', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'zipCode', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'sexe', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'age', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'evenements', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'utilisateur', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'LatLng', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'isPublished'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'titre', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'isFinish', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'atCreated', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'nbrViews', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'nomAnimal', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'espece', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'address', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'ville', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'pays', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'zipCode', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'sexe', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'age', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'evenements', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'utilisateur', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'LatLng', '' . "\0" . 'App\\Entity\\Annonce' . "\0" . 'isPublished'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Annonce $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', []);

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre(string $titre): \App\Entity\Annonce
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', [$titre]);

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType(string $type): \App\Entity\Annonce
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\Annonce
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsFinish(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsFinish', []);

        return parent::getIsFinish();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsFinish(bool $isFinish): \App\Entity\Annonce
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsFinish', [$isFinish]);

        return parent::setIsFinish($isFinish);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtCreated(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtCreated', []);

        return parent::getAtCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtCreated(\DateTimeInterface $atCreated): \App\Entity\Annonce
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtCreated', [$atCreated]);

        return parent::setAtCreated($atCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbrViews(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbrViews', []);

        return parent::getNbrViews();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbrViews(int $nbrViews): \App\Entity\Annonce
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbrViews', [$nbrViews]);

        return parent::setNbrViews($nbrViews);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomAnimal(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomAnimal', []);

        return parent::getNomAnimal();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomAnimal(string $nomAnimal): \App\Entity\Annonce
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomAnimal', [$nomAnimal]);

        return parent::setNomAnimal($nomAnimal);
    }

    /**
     * {@inheritDoc}
     */
    public function getEspece(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEspece', []);

        return parent::getEspece();
    }

    /**
     * {@inheritDoc}
     */
    public function setEspece(string $espece): \App\Entity\Annonce
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEspece', [$espece]);

        return parent::setEspece($espece);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getZipCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZipCode', []);

        return parent::getZipCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setZipCode($zipCode): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZipCode', [$zipCode]);

        parent::setZipCode($zipCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexe(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexe', []);

        return parent::getSexe();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexe(string $sexe): \App\Entity\Annonce
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexe', [$sexe]);

        return parent::setSexe($sexe);
    }

    /**
     * {@inheritDoc}
     */
    public function getAge(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAge', []);

        return parent::getAge();
    }

    /**
     * {@inheritDoc}
     */
    public function setAge(int $age): \App\Entity\Annonce
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAge', [$age]);

        return parent::setAge($age);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvenements(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvenements', []);

        return parent::getEvenements();
    }

    /**
     * {@inheritDoc}
     */
    public function addEvenement(\App\Entity\Evenement $evenement): \App\Entity\Annonce
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEvenement', [$evenement]);

        return parent::addEvenement($evenement);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEvenement(\App\Entity\Evenement $evenement): \App\Entity\Annonce
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEvenement', [$evenement]);

        return parent::removeEvenement($evenement);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtilisateur(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtilisateur', []);

        return parent::getUtilisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setUtilisateur(?\App\Entity\User $utilisateur): \App\Entity\Annonce
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUtilisateur', [$utilisateur]);

        return parent::setUtilisateur($utilisateur);
    }

    /**
     * {@inheritDoc}
     */
    public function isFavori(\App\Entity\User $user): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isFavori', [$user]);

        return parent::isFavori($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', []);

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille($ville): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', [$ville]);

        parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getPays()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPays', []);

        return parent::getPays();
    }

    /**
     * {@inheritDoc}
     */
    public function setPays($pays): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPays', [$pays]);

        parent::setPays($pays);
    }

    /**
     * {@inheritDoc}
     */
    public function getLatLng()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatLng', []);

        return parent::getLatLng();
    }

    /**
     * {@inheritDoc}
     */
    public function setLatLng($LatLng): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatLng', [$LatLng]);

        parent::setLatLng($LatLng);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsPublished(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsPublished', []);

        return parent::getIsPublished();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsPublished(bool $isPublished): \App\Entity\Annonce
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsPublished', [$isPublished]);

        return parent::setIsPublished($isPublished);
    }

}
